// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj9jP9yrKvdc5patA1WC23oNMC0JI6yz8',
    appId: '1:909437743034:web:a21c5f00fa680991e23783',
    messagingSenderId: '909437743034',
    projectId: 'expense-tracker-22d4b',
    authDomain: 'expense-tracker-22d4b.firebaseapp.com',
    storageBucket: 'expense-tracker-22d4b.appspot.com',
    measurementId: 'G-KX4DZCBTC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgtGbDuV1WS_El70ET7swdAj4cf5BwBY0',
    appId: '1:909437743034:android:c5cec5f99783b81ae23783',
    messagingSenderId: '909437743034',
    projectId: 'expense-tracker-22d4b',
    storageBucket: 'expense-tracker-22d4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlbCGlFPGCXGB6eDzhye3ZVQN2Vb4smCg',
    appId: '1:909437743034:ios:c63a5c807411f2bfe23783',
    messagingSenderId: '909437743034',
    projectId: 'expense-tracker-22d4b',
    storageBucket: 'expense-tracker-22d4b.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlbCGlFPGCXGB6eDzhye3ZVQN2Vb4smCg',
    appId: '1:909437743034:ios:c63a5c807411f2bfe23783',
    messagingSenderId: '909437743034',
    projectId: 'expense-tracker-22d4b',
    storageBucket: 'expense-tracker-22d4b.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj9jP9yrKvdc5patA1WC23oNMC0JI6yz8',
    appId: '1:909437743034:web:299bd53664f2e0dbe23783',
    messagingSenderId: '909437743034',
    projectId: 'expense-tracker-22d4b',
    authDomain: 'expense-tracker-22d4b.firebaseapp.com',
    storageBucket: 'expense-tracker-22d4b.appspot.com',
    measurementId: 'G-W1VEK7C6VT',
  );

}